name: Tests + Linting Python
on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch: ~
jobs:
  lint_python:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: python -m pip install --upgrade pip
      - run: pip install flake8 pytest
      - run: pip install -r requirements.txt
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: PYTHONPATH=scrapers pytest
