name: Test run of scrapers

on:
  push:
    branches: [ master ]
    paths:
    - 'scrapers/**'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'scrapers/**'
    - '.github/workflows/**'
  workflow_dispatch: ~

jobs:
  validate:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        npm ci
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements-ocr.txt
        sudo apt-get install poppler-utils

    - name: Test run of all scrapers
      run: ./scrapers/test_scraper.sh

